# --- !Ups
create table FLOWCHART_BLOCKS (
  ID int generated by default as identity(start with 1) not null primary key,
  QUESTION varchar not null
);

create table FLOWS(
  ID int generated by default as identity(start with 1) not null primary key,
  STARTING_BLOCK int not null,
  RESPONSE varchar not null,
  NEXT_BLOCK int not null,
  FOREIGN KEY (STARTING_BLOCK) REFERENCES FLOWCHART_BLOCKS(ID),
  FOREIGN KEY (NEXT_BLOCK)REFERENCES FLOWCHART_BLOCKS(ID)
);

create table FLOWCHARTS(
  ID int generated by default as identity(start with 1) not null primary key,
  NAME varchar not null,
  SIDE varchar not null,
  STARTING_BLOCK int not null,
  FOREIGN KEY(STARTING_BLOCK) REFERENCES FLOWCHART_BLOCKS(ID)
  );

insert into FLOWCHART_BLOCKS(id,question) values(1,'Reassessment possible?');
insert into FLOWCHART_BLOCKS(id,question) values(2,'Playable non-Jihadist Event?');
insert into FLOWCHART_BLOCKS(id,question) values(3,'Play Event');
insert into FLOWCHART_BLOCKS(id,question) values(4,'Unassociated?');
insert into FLOWCHART_BLOCKS(id,question) values(5,'End');
insert into FLOWCHART_BLOCKS(id,question) values(6,'Attempt Reassessment');
insert into FLOWCHART_BLOCKS(id,question) values(7,'Disrupt at Muslim with at least 2 more Cells than TandM and JSP?');
insert into FLOWCHART_BLOCKS(id,question) values(8,'IR >3 and RC possible?');
insert into FLOWCHART_BLOCKS(id,question) values(9,'WOI in Muslim with DRM >=0?');
insert into FLOWCHART_BLOCKS(id,question) values(10,'Add card value to US Reserves');
insert into FLOWCHART_BLOCKS(id,question) values(11,'Homeland Security');
insert into FLOWCHART_BLOCKS(id,question) values(12,'Disrupt');
insert into FLOWCHART_BLOCKS(id,question) values(13,'Regime Change');
insert into FLOWCHART_BLOCKS(id,question) values(14,'WOI Muslim at highest DRM');
insert into FLOWCHART_BLOCKS(id,question) values(15,'DISRUPT DUPLICATE');
insert into FLOWCHART_BLOCKS(id,question) values(16,'WOI in Muslim with DRM of -1?');
insert into FLOWCHART_BLOCKS(id,question) values(17,'Disrupt for +Prestige or to place Cadre');
insert into FLOWCHART_BLOCKS(id,question) values(18,'Regime Change possible?');
insert into FLOWCHART_BLOCKS(id,question) values(19,'Prestige Low?');
insert into FLOWCHART_BLOCKS(id,question) values(20,'Disrupt for +Prestige?');
insert into FLOWCHART_BLOCKS(id,question) values(21,'WOI Muslim at DRM of -1');
insert into FLOWCHART_BLOCKS(id,question) values(22,'Deploy');
insert into FLOWCHART_BLOCKS(id,question) values(23,'Deploy possible?');
insert into FLOWCHART_BLOCKS(id,question) values(24,'US Soft?');
insert into FLOWCHART_BLOCKS(id,question) values(25,'WOI non-Muslim');


insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (1,1,'No',2);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (2,1,'Yes',6);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (3,2,'No',7);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (4,2,'Yes',3);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (5,3,'Next',4);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (6,4,'No',5);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (7,4,'Yes',10);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (8,6,'Fail',2);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (9,7,'No',8);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (10,7,'Yes',12);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (11,8,'No',9);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (12,8,'Yes',13);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (13,9,'No',19);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (14,9,'Yes',14);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (15,16,'No',11);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (16,16,'Yes',21);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (17,17,'No',16);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (18,17,'Yes',12);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (19,18,'No',17);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (20,18,'Yes',13);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (21,19,'No',23);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (22,19,'Yes',20);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (23,20,'No',24);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (24,20,'Yes',15);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (25,23,'No',18);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (26,23,'Yes',22);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (27,24,'No',23);
insert into FLOWS (ID,STARTING_BLOCK,RESPONSE,NEXT_BLOCK) values (28,24,'Yes',25);

insert into FLOWCHARTS(ID ,NAME ,SIDE ,STARTING_BLOCK) values (1,'Post-Alert Resolution Flowchart','US',1);

# --- !Downs

drop table FLOWCHARTS if exists;
drop table Flows if exists;
drop table FLOWCHART_BLOCKS if exists;